Ali Mohammed Taresh Ali

ali7136267922gmail.com

# 1. Create a 3x3x3 array with random values 

In [3]:
import numpy as np
arr = np.random.random((3,3,3))
print(arr)

[[[0.72438805 0.60026344 0.01582548]
  [0.68047667 0.93935256 0.89047479]
  [0.32738491 0.3799784  0.64916784]]

 [[0.15375549 0.14046895 0.83810169]
  [0.94935191 0.60360005 0.87801015]
  [0.15335687 0.31830555 0.54531274]]

 [[0.49980388 0.15133391 0.77619344]
  [0.53683993 0.76761801 0.80525977]
  [0.01123384 0.46922081 0.78082882]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [7]:
diag = np.eye(5,5)
for i in range(1,5):
    diag[i,i-1] = i
print(diag)

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 2. 1. 0. 0.]
 [0. 0. 3. 1. 0.]
 [0. 0. 0. 4. 1.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [9]:
import numpy as np
arr = np.zeros((8,8))
#i=0
arr[1::2,::2]=1
arr[::2,1::2]=1
print(arr.astype(int))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [10]:
import numpy as np
arr = np.random.rand(5,5)
print("Array: ",arr)
normal = np.linalg.norm(arr)
normal_array=arr/normal
print("Normalized Array:",normal_array)

Array:  [[0.76359099 0.48942925 0.1202162  0.10587162 0.95548973]
 [0.40902848 0.67047515 0.77563926 0.38332426 0.99126319]
 [0.70159044 0.82577418 0.43742633 0.17378925 0.83047771]
 [0.72324681 0.63904301 0.19916912 0.18056762 0.8080112 ]
 [0.4003823  0.29081297 0.71086843 0.69481193 0.64467178]]
Normalized Array: [[0.2477443  0.15879353 0.03900371 0.03434966 0.31000514]
 [0.13270779 0.2175332  0.25165332 0.12436815 0.32161171]
 [0.22762844 0.2679194  0.14192137 0.05638528 0.26944545]
 [0.23465478 0.20733516 0.06461969 0.0585845  0.26215627]
 [0.12990257 0.0943532  0.23063866 0.22542918 0.2091614 ]]


# 5.  How to find common values between two arrays?

In [11]:
a1 = np.array([1,2,6,3,4,5,7,9])
a2= np.array([11,6,8,12,3,77,30,9,55,81])
print("Common Values: ",np.intersect1d(a1,a2))

Common Values:  [3 6 9]


# 6.How to get the dates of yesterday, today and tomorrow?

In [13]:
import datetime
today=datetime.date.today()
yesterday=today - datetime.timedelta(days=1)
tomorrow = today+datetime.timedelta(days=1)

print("Yesterday: ",yesterday)
print("Today: ",today)
print("Tomorrow: ",tomorrow)

Yesterday:  2020-07-24
Today:  2020-07-25
Tomorrow:  2020-07-26


# 7. Consider two random array A and B, check if they are equal

In [14]:
a3=np.random.rand(3,3)
a4=np.random.rand(3,3)
print("a3:",a3)
print("a4:",a4)
if (a3==a4).all():
    print("They are equal")
else:
    print("They are not equal")

a3: [[0.77467577 0.9119845  0.70945796]
 [0.02246885 0.45944494 0.27110989]
 [0.81581627 0.62806651 0.45191399]]
a4: [[0.35315342 0.79291774 0.76280421]
 [0.67425786 0.26725463 0.60394545]
 [0.35643548 0.76108933 0.96356693]]
They are not equal


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [3]:
import numpy as np
a = np.random.random(10)
print("Original array:")
print(a)
a[a.argmax()] = 0
print("Maximum value replaced by 0:")
print(a)

Original array:
[0.00273062 0.1656022  0.74963331 0.35009064 0.67773454 0.35886288
 0.92963131 0.14855443 0.23029467 0.31482235]
Maximum value replaced by 0:
[0.00273062 0.1656022  0.74963331 0.35009064 0.67773454 0.35886288
 0.         0.14855443 0.23029467 0.31482235]


# 9. How to print all the values of an array?

In [15]:
a6 = np.array([[10,12,30],[11,22,33],[22,55,88]])
print(a6)

[[10 12 30]
 [11 22 33]
 [22 55 88]]


# 10.Subtract the mean of each row of a matrix

In [16]:
matrix = np.random.rand(2,2)
print(matrix)
new_matrix = matrix - matrix.mean(axis=1,keepdims=True)
print(new_matrix)

[[0.61944602 0.54715533]
 [0.57691628 0.55225431]]
[[ 0.03614535 -0.03614535]
 [ 0.01233098 -0.01233098]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [7]:
import numpy as np
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 6. 2. 3. 4. 2. 1. 3. 3. 2.]


# 12.How to get the diagonal of a dot product?

In [2]:
import numpy as np
arr3 = np.random.randint(0,10,(3,3))
arr4= np.random.randint(0,10,(3,3))

print(arr3)
print(arr4)
np.diag(np.dot(arr3, arr4))

[[7 3 2]
 [5 8 6]
 [3 2 3]]
[[9 2 2]
 [5 4 9]
 [1 7 9]]


array([80, 84, 51])

# 13.How to find the most frequent value in an array?

In [2]:
import numpy as np
m = np.random.randint(0,10,10)
print (m)
print('Frequent Number:', np.bincount(m).argmax())

[8 3 6 7 7 7 3 3 6 3]
Frequent Number: 3


# 14.How to get the n largest values of an array

In [5]:
import numpy as np
x=np.arange(45)
print(x)
np.random.shuffle(x)
n=1
print(x[np.argsort(x)[-n:]])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44]
[44]


In [6]:
np.max(x)

44

# 15.How to create a record array from a regular array?

In [3]:
import numpy as np
a =np.array(['Hello','Byee','Hello World'])
b=np.array([10,20,30])
c=np.array(['a','b','c'])
result=np.core.records.fromarrays([a,b,c])

In [4]:
print(result[0])
print(result[1])
print(result[2])

('Hello', 10, 'a')
('Byee', 20, 'b')
('Hello World', 30, 'c')
