In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('Dataset/train.csv')
df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [3]:
df = df.drop(['Name','PassengerId','Ticket','Cabin'],axis=1)

In [4]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [5]:
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix

In [7]:
en = LabelEncoder()
df['Sex'] = en.fit_transform(df['Sex'])
df['Embarked'] = en.fit_transform(df['Embarked'])

In [21]:
def navb(col):
    y = df[col]
    X = df.drop([col],axis = 1)
    X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.25,random_state = 0)
    nbclf = GaussianNB()
    ypred = nbclf.fit(X_train,y_train).predict(X_test)
    ac = accuracy_score(y_test,ypred)
    cm = confusion_matrix(y_test,ypred)
    
    print("Accuracy Score : ",ac)
    print('                    ')
    print("Confusion Matrix :  \n",cm)
    

In [22]:
navb('Sex')

Accuracy Score :  0.7174887892376681
                    
Confusion Matrix :  
 [[ 46  36]
 [ 27 114]]


In [23]:
navb('Pclass')

Accuracy Score :  0.7040358744394619
                    
Confusion Matrix :  
 [[41 10  8]
 [ 4 21 17]
 [ 4 23 95]]


In [24]:
navb('SibSp')

Accuracy Score :  0.5829596412556054
                    
Confusion Matrix :  
 [[113   7   0  33   1   0   0]
 [ 24   7   0  18   2   0   0]
 [  5   0   1   0   1   0   0]
 [  0   0   0   4   2   0   0]
 [  0   0   0   0   2   0   0]
 [  0   0   0   0   0   1   0]
 [  0   0   0   0   0   0   2]]


In [25]:
navb('Embarked')

Accuracy Score :  0.7040358744394619
                    
Confusion Matrix :  
 [[ 17   2  20]
 [  0   8  13]
 [ 17  14 132]]


In [26]:
navb('Parch')

Accuracy Score :  0.5919282511210763
                    
Confusion Matrix :  
 [[122  10   0  25   9]
 [ 12   4   1  11   3]
 [  5   5   6   6   2]
 [  0   0   0   0   1]
 [  0   0   0   1   0]]


-----------------------